### ISSUE TITLE
How to make sure this is the minimum solution

### ISSUE THREAD

**Issue by 972023111** [ShootMe/MinimalKlondike#2]
thanks for sharing this solution , but I hava some questions.

1.How to make sure this is the minimum solution?

2.It's hard for me to understand the solve process , Can share your thinking?

thanks.

**Comment by ShootMe** [comment]
The solver does a breadth first search of all possible moves. So unless I missed a certain scenario in the logic, this will assuming you have enough memory, always return the minimal solution or tell you the deal is impossible.
