### ISSUE TITLE
Where I made an error ?

### ISSUE THREAD

**Issue by only4everock** [ShootMe/MinimalKlondike#6]
this is my klondike command : Klondike.exe  062122133041014042081034084111053124132083091113022071074023082033131021061104043064092054134 

this is my cards : 6D,??,??,??,??,??,??,
	QD,??,??,??,??,??,??,
		KH,??,??,??,??,
			4C,??,??,??,
				AS,??,??,
					4D,??,
						8C,

and this is deck(drawing cards) : 3S,8S,JC,5H,QS,KD,8H,9C,JH,2D,7C,7S,2H,8D,3H,KC,2C,6C,10S,4H,6S,9D,5S,KS

when I run command witout initial move. it gives this output : Klondike.exe  062122133041014042081034084111053124132083091113022071074023082033131021061104043064092054134
Deal: 031112012094033022071023111021072032122104064121043062044133061024073114082052054083102134124074132013081053092011113084034103091014051063042093131101123041

  A        B  C  D  E

  F  G  H  I  J  K  L
+3C JD AD 9S 3H 2D 7C
   +2H JC 2C 7D 3D QD
      +TS 6S QC 4H 6D
         +4S KH 6C 2S
            +7H JS 8D
               +5D 5S
                  +8H

 TD KS QS 7S KD AH 8C
 5H 9D AC JH 8S 3S TH
 9C AS 5C 6H 4D 9H KC
 TC QH 4C

Moves: IK KI @AK @@@AL @@AE GE @@@@AB AH HG @@AG JG IG IB FB JF AJ @@AH @AH @AD LI IK @@AK @@@AI @AJ @@AB AI LK LH LD AJ AK AB AD JF KI AK AF JF JE KF KE FE FB IL IE KG LI HL HC KC GC GD IC GC ID GD GE IC FC ID GD IE LC GC ID GD IC GC ID LI LC LB FB FE IB FB IE FE IB FB IE FE IB AC AD AD

(Deal Result: Minimal Foundation: 52 Moves: 110 Rounds: 1 States: 3272426 Took: 00:00:08.9502218)
Done 00:00:09.1256026 in description you said + represents visible card but I dont have 3c at my screen. and my game version does'nt allow undo action. Here is the screenshot of fresh game . 
![image](https://github.com/ShootMe/MinimalKlondike/assets/58207188/7b39e036-5e98-42f2-9985-05dad7bf5ed2)
in moves it says IK KI it means table4 to 6 but you cant move 4C to 4D
any help appreciated.

**Comment by ShootMe** [comment]
This solver requires all card info to work. So without knowing what all the cards are it is not going to work.
